[package]
name = "ermc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.2"
tokio = {
	version = "1.53.1",
	features = ["full"]
}
serde = {
	version = "1.0.229",
	features = ["derive"]
}
reqwest = {
	version = "0.13.4",
	features = ["json"]
}
anyhow = "1.0.104"
toml = "1.1.4"
redis = {
	version = "1.6.0",
	features = ["tokio-comp"]
}
futures-util = "0.3.34"
rusqlite = {
	version = "0.40.2",
	features = ["bundled"]
}

[profile.release]
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "s"
